### PR TITLE
Include example for how to deploy Eve on AWS

### PR DESCRIPTION
**Pull request by KFishner**
I'm hoping this lowers the barrier to entry for using Eve in a more realistic use case on AWS, rather than just Heroku. 

Let me know if this is helpful!

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
I'd rather prefer to keep the Eve-Demo project as simple and to the point as possible. However, should you be willing to write a blog post on deploying Eve on AWS through your service, then I would be more than willing to link it on the eve website (maybe on a external resources page)

**Comment by KFishner** [comment]
Definitely makes sense. 

I have a thorough [walkthrough here](https://github.com/hashicorp/atlas-examples/tree/master/PythonAPI-MongoDB). Does that work as a link on the Eve website or would you prefer a more blog-esque format?

**Comment by nicolaiarocci** [comment]
Yeah it's good. I plan to add a Resources pages to the official documentation, that's where it'll be added.

**Comment by nicolaiarocci** [comment]
Oh and also: https://twitter.com/nicolaiarocci/status/571214524898017280

**Comment by KFishner** [comment]
Oh nice, thanks Nicola!

**Pull request closed without merging**
